### ISSUE TITLE
bower ENORESTARGET  URL sources can't resolve targets

### ISSUE THREAD

**Issue by kirantpatil** [benoithubert/sails-ember-carpooling#7]
Hi,

bower install shows the "bower ENORESTARGET  URL sources can't resolve targets" error.

 kpatil  ⋯  carpool  sails-ember-carpooling  frontend-public  bower install    
bower cached        git://github.com/jquery/qunit.git#1.17.1
bower validate      1.17.1 against git://github.com/jquery/qunit.git#~1.17.1
bower cached        git://github.com/chriso/validator.js.git#4.2.0
bower validate      4.2.0 against git://github.com/chriso/validator.js.git#*
bower cached        git://github.com/alexei/sprintf.js.git#1.0.3
bower validate      1.0.3 against git://github.com/alexei/sprintf.js.git#*
bower cached        git://github.com/uikit/bower-uikit.git#2.23.0
bower validate      2.23.0 against git://github.com/uikit/bower-uikit.git#*
bower cached        git://github.com/components/ember-data.git#1.0.0-beta.16
bower validate      1.0.0-beta.16 against git://github.com/components/ember-data.git#1.0.0-beta.16
bower cached        git://github.com/rwjblue/ember-qunit-builds.git#0.2.8
bower validate      0.2.8 against git://github.com/rwjblue/ember-qunit-builds.git#0.2.8
bower cached        git://github.com/stefanpenner/ember-jj-abrams-resolver.git#0.1.21
bower validate      0.1.21 against git://github.com/stefanpenner/ember-jj-abrams-resolver.git#~0.1.14
bower cached        git://github.com/victorquinn/chancejs.git#0.8.0
bower validate      0.8.0 against git://github.com/victorquinn/chancejs.git#*
bower cached        git://github.com/components/highlightjs.git#8.8.0
bower validate      8.8.0 against git://github.com/components/highlightjs.git#*
bower cached        git://github.com/ember-cli/ember-cli-test-loader.git#0.1.3
bower validate      0.1.3 against git://github.com/ember-cli/ember-cli-test-loader.git#0.1.3
bower cached        git://github.com/lodash/lodash.git#3.10.1
bower validate      3.10.1 against git://github.com/lodash/lodash.git#*
bower cached        git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
bower validate      0.0.7 against git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
bower cached        git://github.com/instructure/ic-ajax.git#2.0.2
bower validate      2.0.2 against git://github.com/instructure/ic-ajax.git#*
bower cached        git://github.com/moment/moment.git#2.10.6
bower validate      2.10.6 against git://github.com/moment/moment.git#*
bower cached        git://github.com/machty/emblem.js.git#0.6.1
bower validate      0.6.1 against git://github.com/machty/emblem.js.git#*
bower cached        git://github.com/components/ember.git#1.10.0
bower validate      1.10.0 against git://github.com/components/ember.git#1.10.0
bower cached        git://github.com/jquery/jquery.git#1.11.3
bower validate      1.11.3 against git://github.com/jquery/jquery.git#^1.11.1
bower ENORESTARGET  URL sources can't resolve targets

Thanks.

**Comment by kirantpatil** [comment]
The below command asking me to do "bower install" to install missing dependencies.

 kpatil  ⋯  carpool  sails-ember-carpooling  frontend-public  ember server 
--proxy http://127.0.0.1:1337

Missing bower packages: 
Package: jquery
  * Specified: latest
  * Installed: (not installed)

Package: ember
  * Specified: 1.10.0
  * Installed: (not installed)

Package: ember-data
  * Specified: 1.0.0-beta.16
  * Installed: (not installed)

Package: ember-resolver
  * Specified: ~0.1.14
  * Installed: (not installed)

Package: loader.js
  * Specified: ember-cli/loader.js#3.2.0
  * Installed: (not installed)

Package: ember-cli-shims
  * Specified: ember-cli/ember-cli-shims#0.0.3
  * Installed: (not installed)

Package: ember-cli-test-loader
  * Specified: ember-cli-test-loader#0.1.3
  * Installed: (not installed)

Package: ember-load-initializers
  * Specified: ember-cli/ember-load-initializers#0.0.2
  * Installed: (not installed)

Package: ember-qunit
  * Specified: 0.2.8
  * Installed: (not installed)

Package: ember-qunit-notifications
  * Specified: 0.0.7
  * Installed: (not installed)

Package: qunit
  * Specified: ~1.17.1
  * Installed: (not installed)

Package: uikit
  * Specified: latest
  * Installed: (not installed)

Package: highlightjs
  * Specified: latest
  * Installed: (not installed)

Package: moment
  * Specified: latest
  * Installed: (not installed)

Package: validator-js
  * Specified: latest
  * Installed: (not installed)

Package: emblem
  * Specified: latest
  * Installed: (not installed)

Package: chance
  * Specified: latest
  * Installed: (not installed)

Package: sprintf
  * Specified: latest
  * Installed: (not installed)

Package: lodash
  * Specified: latest
  * Installed: (not installed)

Package: ic-ajax
  * Specified: latest
  * Installed: (not installed)

Run `bower install` to install missing dependencies.

**Comment by benoithubert** [comment]
`bower install` failed, so Ember CLI can't start.
Try this (source [here](http://wildlyinaccurate.com/force-bower-to-clone-from-https-instead-of-git/) ):

    git config --global url.https://.insteadOf git://

And then try running `bower install` again. I stumbled upon this issue quite a while ago and don't remind the exact cause. It's a Bower related issue and there's not much I can do about it unfortunately !!
Good luck

**Comment by kirantpatil** [comment]
Even after doing it the problem still persists.

wer cached        git://github.com/alexei/sprintf.js.git#1.0.3
bower validate      1.0.3 against git://github.com/alexei/sprintf.js.git#*
bower cached        git://github.com/lodash/lodash.git#3.10.1
bower validate      3.10.1 against git://github.com/lodash/lodash.git#*
bower cached        git://github.com/instructure/ic-ajax.git#2.0.2
bower validate      2.0.2 against git://github.com/instructure/ic-ajax.git#*
bower ENORESTARGET  URL sources can't resolve targets

 kpatil  ⋯  carpool  sails-ember-carpooling  frontend-public  git config --list
--
user.email=kirantpatil@gmail.com
user.name=Kiran Patil
url.https://.insteadof=git://
url.https://github.com/.insteadof=git@github.com:
url.https://github.insteadof=git://github
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/benoithubert/sails-ember-carpooling.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
url.https://.insteadof=git://
url.https://github.com/.insteadof=git@github.com:

**Comment by benoithubert** [comment]
Try `bower cache clean` ??

**Comment by kirantpatil** [comment]
I did "bower cache clean" and some of the packages resolved but the result
remain same as below.

bower download
https://github.com/rwjblue/ember-qunit-builds/archive/v0.2.8.tar.gz
bower download      https://github.com/jquery/qunit/archive/1.17.1.tar.gz
bower download      https://github.com/jquery/jquery/archive/1.11.3.tar.gz
bower download      https://github.com/moment/moment/archive/2.10.6.tar.gz
bower download
https://github.com/victorquinn/chancejs/archive/0.8.0.tar.gz
bower download
https://github.com/alexei/sprintf.js/archive/1.0.3.tar.gz
bower extract       ember-resolver#~0.1.14 archive.tar.gz
bower download
https://github.com/dockyard/ember-qunit-notifications/archive/v0.0.7.tar.gz
bower download
https://github.com/instructure/ic-ajax/archive/v2.0.2.tar.gz
bower resolved      git://
github.com/stefanpenner/ember-jj-abrams-resolver.git#0.1.21
bower extract       qunit#~1.17.1 archive.tar.gz
bower resolved      git://github.com/jquery/qunit.git#1.17.1
bower download      https://github.com/lodash/lodash/archive/3.10.1.tar.gz
bower ENORESTARGET  URL sources can't resolve targets

**Comment by kirantpatil** [comment]
Sir,

Any updates on this issue ?

Thanks.

**Comment by benoithubert** [comment]
I'm sorry, I'm very busy right now, I'm afraid I can't help you right now.

2015-11-05 10:50 GMT+01:00 kirantpatil <notifications@github.com>:

> Sir,
>
> Any updates on this issue ?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benoithubert/sails-ember-carpooling/issues/7#issuecomment-154009515>
> .
>



-- 
Benoît Hubert
Développeur web : https://benoithubert.net
Professeur de yoga : http://yogatoutcourt.com/planning/les-profs/
Tél. : 06 61 21 62 12

**Comment by kirantpatil** [comment]
Thank you, I will keep on trying and in any case if I can overcome it will
inform you.

**Comment by kirantpatil** [comment]
Dear @benoithubert,

Any updates on this issue ?

When can I expect a working copy of this project ?

Thanks.

**Comment by kirantpatil** [comment]
Since, to understand the project once it starts running may take some time for us. So the sooner it is up we could start the work.

**Comment by kirantpatil** [comment]
Closing this since we started using 'latest' instead of version name which resolved the issue. Feel free to reopen it.
